---
#- name: Installing sudo packages using apt
#  become: true
#  apt:
#    pkg: "sudo"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'Ubuntu'

#- name: Installing sudo packages using yum
#  become: true
#  yum:
#    pkg: "sudo"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


#- name: Installing sudo packages using pacman
#  pacman:
#    name: "sudo"
#    state: present
#  when: ansible_distribution == 'MacOSX'

- name: Installing sudo packages
  become: true
  package:
    name: "sudo"
    state: present
